/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 *	Note: In this example, an Arduino is used as the I2C slave device.
 *	The Arduino code was published by niekiran at:
 *	https://github.com/niekiran/MasteringMCU/tree/master/Resources/Arduino/i2c/001I2CSlaveRxString.ino
 */

#include <stdint.h>
#include <string.h>
#include "stm32f103xx.h"

#define SLAVE_ADDR 0x68

// Create and configure the handle structure for I2C1
I2C_Handle_t I2C1handle;

// Simple delay function
void delay(void)
{
    for(uint32_t i = 0; i < 500000/2 ; i++);
}

// Configure GPIO pins for I2C1
void I2C1_GPIO_Init(void)
{
	GPIO_Handle_t I2CPins;
	I2CPins.pGPIOx = GPIOB;
	I2CPins.GPIO_PinConfig.PinMode = GPIO_MODE_AF_OPEN_DRAIN;
	I2CPins.GPIO_PinConfig.PinSpeed = GPIO_SPEED_OUTPUT_10MHZ;

	// SCL
	I2CPins.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_6;
	GPIO_Init(&I2CPins);

	// SDA
	I2CPins.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_7;
	GPIO_Init(&I2CPins);
}

// Configure I2C1
void I2C1_Init(void)
{
	// Configure the handle structure for I2C1
	I2C1handle.pI2Cx = I2C1;
	I2C1handle.I2C_Config.I2C_ACKControl = I2C_ACK_ENABLE;
	I2C1handle.I2C_Config.I2C_FMDutyycle = I2C_FM_DUTY_2;
	I2C1handle.I2C_Config.I2C_SCLSpeed = I2C_SCL_SPEED_SM;

	// Initialize the I2C1 with the configured settings
	I2C_Init(&I2C1handle);
}

// Initialize GPIO for button input (PB5)
void GPIO_Button_Init(void)
{
    // Create and configure the handle structure for Button GPIO (PB5)
    GPIO_Handle_t GPIOButton;

    GPIOButton.pGPIOx = GPIOB;                           			// Set GPIO port to GPIOB
    GPIOButton.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_5; 			// Set pin number 5
    GPIOButton.GPIO_PinConfig.PinSpeed = GPIO_SPEED_INPUT;			// Set pin as input
    GPIOButton.GPIO_PinConfig.PinMode = GPIO_MODE_INPUT_PU_PD; 		// S pin with pull-up/pull-down

    // Initialize the GPIO pin 5 with the configured settings
    GPIO_Init(&GPIOButton);
}


int main(void)
{
	// Data to send over I2C
	char user_data[] = "Hello World";

	// Initialize I2C and button GPIO
	I2C1_GPIO_Init();												// Configure I2C pins
	I2C1_Init();													// Configure I2C1 peripheral
	GPIO_Button_Init();												// Initialize button pin

	// Enable the i2c peripheral
	I2C_PeripheralControl(I2C1, ENABLE);

	while(1)
	{
		// Wait for button press
		while (GPIO_ReadFromInputPin(GPIOB, GPIO_PIN_NO_5) == 0);
		delay();													// Simple debounce delay

		// Send data
		I2C_MasterSendData(&I2C1handle, (uint8_t*)user_data, strlen(user_data), SLAVE_ADDR, I2C_DISABLE_SR);
	}
}


