/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 *	Note: In this example, an Arduino is used as a device.
 *	The Arduino code was published by niekiran at:
 *	https://github.com/niekiran/MasteringMCU/blob/master/Resources/Arduino/usart/001UARTRxString/001UARTRxString.ino
 */

#include <stdio.h>
#include <string.h>
#include "stm32f103xx.h"

char msg[124] = "Hello\n\R";

// Create and configure the handle structure for USART2
USART_Handle_t USART2handle;

// Simple delay function
void delay(void)
{
    for(uint32_t i = 0; i < 500000/2 ; i++);
}

// Configure GPIO pins for USART2
void USART2_GPIO_Init(void)
{
	GPIO_Handle_t USARTPins;
	USARTPins.pGPIOx = GPIOA;
	USARTPins.GPIO_PinConfig.PinMode = GPIO_MODE_AF_PUSH_PULL;
	USARTPins.GPIO_PinConfig.PinSpeed = GPIO_SPEED_OUTPUT_10MHZ;

	// PA2 (TX)
	USARTPins.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_2;
	GPIO_Init(&USARTPins);

	// PA3 (RX)
	USARTPins.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_3;
	GPIO_Init(&USARTPins);
}

//Configure USART2
void USART2_Init(void)
{
	// Configure the handle structure for USART2
	USART2handle.pUSARTx = USART2;
	USART2handle.USART_Config.USART_Baud = USART_STD_BAUD_9600;
	USART2handle.USART_Config.USART_NoOfStopBits = USART_STOPBITS_1;
	USART2handle.USART_Config.USART_ParityControl = USART_PARITY_DISABLE;
	USART2handle.USART_Config.USART_WordLength = USART_WORDLEN_8BITS;
	USART2handle.USART_Config.USART_HWFlowControl = USART_HW_FLOW_CTRL_NONE;
	USART2handle.USART_Config.USART_Mode = USART_MODE_TX;

	USART_Init(&USART2handle);
}

// Initialize GPIO for button input (PB5)
void GPIO_Button_Init(void)
{
    // Create and configure the handle structure for Button GPIO (PB5)
    GPIO_Handle_t GPIOButton;

    GPIOButton.pGPIOx = GPIOB;                           			// Set GPIO port to GPIOB
    GPIOButton.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_5; 			// Set pin number 5
    GPIOButton.GPIO_PinConfig.PinSpeed = GPIO_SPEED_INPUT;			// Set pin as input
    GPIOButton.GPIO_PinConfig.PinMode = GPIO_MODE_INPUT_PU_PD; 		// S pin with pull-up/pull-down

    // Initialize the GPIO pin 5 with the configured settings
    GPIO_Init(&GPIOButton);
}

int main(void)
{
	USART2_GPIO_Init();
	USART2_Init();
	GPIO_Button_Init();
	USART_PeripheralControl(USART2, ENABLE);

	while(1)
	{
		// Wait for button press
		while (GPIO_ReadFromInputPin(GPIOB, GPIO_PIN_NO_5) == 0);

		delay();		// Simple debounce delay

		USART_SendData(&USART2handle, (uint8_t*)msg, strlen(msg));

	}

	return 0;
}
