/**
  *******************************************************************************
  * @file           : main.c
  * @author         : Auto-generated by STM32CubeIDE
  * @brief          : Main program body for LED control based on button input
  *******************************************************************************
  * @attention
  *
  * Copyright (c) 2025 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  *******************************************************************************
  */

#include <stdint.h>
#include "stm32f103xx.h"

// Simple delay function
void delay(void)
{
    // Simple loop for delay purpose
    for(uint32_t i = 0; i < 500000 ; i++);
}

int main(void)
{
    // Create and configure the handle structure for LED GPIO (PA7)
    GPIO_Handle_t GPIOLed;

    GPIOLed.pGPIOx = GPIOA;											// Set GPIO port to GPIOA
    GPIOLed.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_7;				// Set pin number 7
    GPIOLed.GPIO_PinConfig.PinSpeed = GPIO_SPEED_OUTPUT_10MHZ;		// Set pin speed to 10 MHz
    GPIOLed.GPIO_PinConfig.PinMode = GPIO_MODE_GP_PUSH_PULL;		// Configure pin as general-purpose push-pull output

    // Enable the clock for GPIOA peripheral
      GPIO_PeriClockControl(GPIOA, ENABLE);

    // Initialize the GPIO pin 7 with the configured settings
    GPIO_Init(&GPIOLed);


    // Create and configure the handle structure for Button GPIO (PB5)
    GPIO_Handle_t GPIOButton;

    GPIOButton.pGPIOx = GPIOB;                           			// Set GPIO port to GPIOB
    GPIOButton.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_5; 			// Set pin number 5
    GPIOButton.GPIO_PinConfig.PinSpeed = GPIO_SPEED_INPUT;			// Set pin as input
    GPIOButton.GPIO_PinConfig.PinMode = GPIO_MODE_INPUT_PU_PD; 		// S pin with pull-up/pull-down

    // Enable the clock for GPIOB peripheral
    GPIO_PeriClockControl(GPIOB, ENABLE);                // Enable clock for GPIOB

    // Initialize the GPIO pin 5 with the configured settings
    GPIO_Init(&GPIOButton);

    while(1)
    {
        // Check if the button on GPIOB pin 5 is pressed
        if((GPIO_ReadFromInputPin(GPIOB, GPIO_PIN_NO_5)) == SET)
        {
            // Turn on the LED (PA7) when the button is pressed
            GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_7, SET); // LED ON
        }
        else
        {
            // Turn off the LED (PA7) when the button is not pressed
            GPIO_WriteToOutputPin(GPIOA, GPIO_PIN_NO_7, RESET); // LED OFF
        }
    }

    return 0;
}
