/**
 *******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program for toggling LED on GPIOA pin 7 with a delay
 *******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 *******************************************************************************
 */

#include <stdint.h>
#include "stm32f103xx.h"

// Simple delay function
void delay(void)
{
	// Simple loop for delay purpose
    for(uint32_t i = 0; i < 500000 ; i++);
}

int main(void)
{
	// Create and configure the handle structure for LED GPIO (PA7)
    GPIO_Handle_t GPIOLed;

    GPIOLed.pGPIOx = GPIOA;											// Set GPIO port to GPIOA
    GPIOLed.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_7;				// Set pin number 7
    GPIOLed.GPIO_PinConfig.PinSpeed = GPIO_SPEED_OUTPUT_10MHZ;		// Set pin speed to 10 MHz
    GPIOLed.GPIO_PinConfig.PinMode = GPIO_MODE_GP_PUSH_PULL;		// Configure pin as general-purpose push-pull output

    // Enable the clock for GPIOA peripheral
    GPIO_PeriClockControl(GPIOA, ENABLE);

    // Initialize the GPIO pin 7 with the configured settings
    GPIO_Init(&GPIOLed);

    while(1)
    {
        // Toggle the state of the GPIO pin 7 (turn the LED on/off)
        GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_7);

        // Call delay to create a visible toggle effect
        delay();
    }

    return 0;
}
