	/**
	 ******************************************************************************
	 * @file           : main.c
	 * @author         : Auto-generated by STM32CubeIDE
	 * @brief          : Main program body
	 ******************************************************************************
	 * @attention
	 *
	 * Copyright (c) 2025 STMicroelectronics.
	 * All rights reserved.
	 *
	 * This software is licensed under terms that can be found in the LICENSE file
	 * in the root directory of this software component.
	 * If no LICENSE file comes with this software, it is provided AS-IS.
	 *
	 ******************************************************************************
	 */

	#include <stdint.h>
	#include "stm32f103xx.h"

	// Simple delay function
	void delay(void)
	{
		// Simple loop for delay purpose
		for(uint32_t i = 0; i < 500000/2 ; i++);
	}


	int main(void)
	{
		// Create and configure the handle structure for LED GPIO (PA7)
		GPIO_Handle_t GPIOLed;

		GPIOLed.pGPIOx = GPIOA;											// Set GPIO port to GPIOA
		GPIOLed.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_7;				// Set pin number 7
		GPIOLed.GPIO_PinConfig.PinSpeed = GPIO_SPEED_OUTPUT_10MHZ;		// Set pin speed to 10 MHz
		GPIOLed.GPIO_PinConfig.PinMode = GPIO_MODE_GP_PUSH_PULL;		// Configure pin as general-purpose push-pull output

	    // Enable the clock for GPIOA peripheral
	      GPIO_PeriClockControl(GPIOA, ENABLE);

	    // Initialize the GPIO pin 7 with the configured settings
	    GPIO_Init(&GPIOLed);

	    // Create and configure the handle structure for Button GPIO (PB5)
		GPIO_Handle_t GPIOButton;

		GPIOButton.pGPIOx = GPIOB;										// Set GPIO port to GPIOB
		GPIOButton.GPIO_PinConfig.PinNumber = GPIO_PIN_NO_5;			// Set pin number 5
		GPIOButton.GPIO_PinConfig.PinSpeed = GPIO_SPEED_INPUT;			// Set pin as input
		GPIOButton.GPIO_PinConfig.PinMode = GPIO_MODE_IT_RISING;		// Set interrupt on rising edge

		// Enable the clock for GPIOB peripheral
		GPIO_PeriClockControl(GPIOB, ENABLE);                // Enable clock for GPIOB

		// Initialize the GPIO pin 5 with the configured settings
		GPIO_Init(&GPIOButton);


		GPIO_IRQInterruptConfig(IRQ_NO_EXTI9_5, ENABLE);				// Enable EXTI line[9:5] interrupt

		while(1);

		return 0;
	}

	// Interrupt Service Routine for EXTI lines 9 to 5
	void EXTI9_5_IRQHandler(void)
	{
		delay();														// Delay for debouncing
		GPIO_IRQHandling(GPIO_PIN_NO_5);								// Clear interrupt pending bit for pin 5
		GPIO_ToggleOutputPin(GPIOA, GPIO_PIN_NO_7);						// Toggle LED on PA7
	}

